# Build de l'application avec maven
FROM maven:3.8.6-openjdk-21 AS builder

WORKDIR /app

# copie du pom.xml et telechargement des dependances
COPY pom.xml .
RUN mvn dependency:go-offline

# copie les fichiers sources et execution de la construction
COPY src ./src
RUN mvn package -DskipTests


FROM openjdk:17

WORKDIR /app

# copie de l'artifact JAR depuis l'etape precedente ( artifactid-version )
COPY --from=builder /app/target/todo-management-0.0.1-SNAPSHOT.jar .

EXPOSE 5001


# Execution de l'application
ENTRYPOINT ["java","-jar","blog-0.0.1-SNAPSHOT.jar"]


